#!/usr/bin/env bash
launchApp(){
    echo "opening $1......"
    
    open "$2" -a "$1"

     
}

main(){

if [ $1 = "list" ]
then
    cat software.txt
else
    while read -r line
    do
        tag="$(cut -d',' -f1 <<<$line)"

        if [ $1 = $tag ]
        then
            app="$(cut -d',' -f2 <<<$line)"
            appName="$(tr '.' ' ' <<<$app)"

            launchApp "$appName" $2
        fi

        
    done <software.txt
fi
}


main $@